prevention of duplicate entries from commands was added

diff --git a/tmux-sessionizer b/tmux-sessionizer
--- a/tmux-sessionizer
+++ b/tmux-sessionizer
@@ -1,27 +1,44 @@
 #/usr/bin/env bash
-#script_dir="$(dirname "$(realpath "$0")")"
+
+# the directory in which the tmux-sessionizer state will be stored
 script_dir="$HOME"
+# the file where the tmux-sessionizer data will be stored
 file_name=".tmux-sessionizer.txt"
 full_path="$script_dir/$file_name" 
 
-command_created_paths=$(mktemp)
-# Any paths that you want to dynamically update on their own, add with
-# commands. These paths are not shown in the tmux-sesionizer list, but they
-# are selectable with tmux-sessionizer. Any directories shown from here cannot
-# be added with tmux-sessionizer -a 
-commands=(
-    #example command, add all directories from your home always.
-    "find $HOME -maxdepth 1 -type d"
-);
-
-for cmd in "${commands[@]}"; do 
-    eval "$cmd" >> $command_created_paths
-done
-
-
+# create the tmux-sessionizer state file that remembers what directories to
+# show
 if [[ ! -e "$full_path" ]]; then
     touch "$full_path"
 fi
+
+# Write any commands here which will add directories that you want to stay
+# up-to-date. Since directories are usually added to $HOME it is probably a
+# good idea to keep the initial example
+commands=(
+    # Example command
+    "find $HOME -maxdepth 1 -type d"
+)
+
+combined_results=""
+
+# Gather the results of all the commands
+for cmd in "${commands[@]}"; do 
+    combined_results+=$(eval "$cmd"; echo)
+done
+
+# if there were any results for the commands we add it to the tmux-sessionizer
+# list, but we also ensure no duplicates are added
+if [[ -n "$combined_results" ]]; then
+    temp_file=$(mktemp)
+    if { echo "$combined_results"; cat "$full_path"; } | sort -u > "$temp_file"; then
+        mv "$temp_file" "$full_path"
+    else
+        echo "Error: Failed to create sorted output."
+        rm -f "$temp_file"
+    fi
+fi
+
 
 #adding, deleting or listing the tmux-sessionizer list
 if [[ $# -eq 1 ]]; then
@@ -34,7 +51,7 @@ if [[ $# -eq 1 ]]; then
             line="${line%/}"
             # ensure that the filepath is absolute and it exists
             if [[ -d $line && "$line" = /* ]]; then
-                if ! grep -qFx $line $full_path $command_created_paths; then
+                if ! grep -qFx $line $full_path ; then
                     echo "$line" >> $full_path
                 fi
             fi
@@ -56,14 +73,25 @@ if [[ $# -eq 1 ]]; then
                 temp_file=$(mktemp)
                 grep -v -F -x -e "$selected" "$full_path" > "$temp_file"
                 mv "$temp_file" "$full_path"
+                rm $temp_file
             fi
         done
+    # simply lists all paths in your tmux-sessionizer list to standard out
     elif [[ $1 == -list || $1 == -l ]]; then
         cat $full_path
     fi
     exit 0
 fi
-# REGULAR USAGE OF TMUX-SESSIONIZER PAST THIS POINT
+
+
+# remove any directories in the tmux-sessionizer list that no longer exist
+valid_paths=$(mktemp)
+while read -r line; do
+    if [[ -d "$line" ]]; then
+        echo "$line" >> $valid_paths
+    fi
+done < "$full_path"
+mv "$valid_paths" "$full_path"
 
 
 # switching tmux to the files
@@ -90,9 +118,7 @@ hydrate() {
 if [[ $# -eq 1 ]]; then
     selected=$1
 else
-    # list all filepaths in the tmux-sessionizer list as well as any filepaths
-    # generated by commands
-    selected=$(cat $full_path $command_created_paths| fzf)
+    selected=$(cat $full_path | fzf)
 fi
 
 if [[ -z $selected ]]; then
